# Generated by Django 5.0.6 on 2024-07-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsorbEapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'notes', 'verbose_name_plural': 'notes'},
        ),
        migrations.AlterField(
            model_name='notes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
