# Generated by Django 5.0.6 on 2024-07-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsorbEapp', '0004_rename_is_finesed_homework_is_finised'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='is_finised',
            new_name='is_finished',
        ),
        migrations.AddField(
            model_name='homework',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='homework_files/'),
        ),
    ]
