# Generated by Django 5.0.6 on 2024-08-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsorbEapp', '0007_homework_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='approval_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
